# Generated by Django 5.2.17 on 2026-09-06 21:58

import cloudinary_storage.storage
import django.db.models.deletion
import engagements.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0006_opportunity_role_skill_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=255)),
                ('role_skill_tags', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('pending_attestation', 'Pending Attestation'), ('attested', 'Attested'), ('disputed', 'Disputed')], default='in_progress', max_length=20)),
                ('attested_at', models.DateTimeField(blank=True, null=True)),
                ('attestation_notes', models.TextField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attested_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='opportunities.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_engagements', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_summary_text', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=engagements.models.certificate_file_path)),
                ('verification_page_url', models.URLField(blank=True, max_length=500, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('revoked_reason', models.TextField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('engagement_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='engagements.engagementrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TaskEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('logged_by', models.CharField(choices=[('volunteer', 'Volunteer'), ('coordinator', 'Coordinator')], default='volunteer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='engagements.engagementrecord')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
