# Generated by Django 5.2.7 on 2026-01-23 11:07

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='document',
            field=models.FileField(upload_to=profiles.models.credential_file_path),
        ),
    ]
