# Generated by Django 5.2.7 on 2026-01-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_pathfinderprofile_languages_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pathfinderprofile",
            old_name="languages",
            new_name="language",
        ),
        migrations.RenameField(
            model_name="pathfinderprofile",
            old_name="skills",
            new_name="skill",
        ),
    ]
