# Generated by Django 5.2.7 on 2026-01-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_rename_languages_pathfinderprofile_language_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pathfinderprofile",
            old_name="language",
            new_name="languages",
        ),
        migrations.RenameField(
            model_name="pathfinderprofile",
            old_name="skill",
            new_name="skills",
        ),
    ]
