# Generated by Django 5.2.7 on 2026-02-19 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_credential_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AddField(
            model_name='enablerprofileextra',
            name='employees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enablerprofileextra',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pathfinderprofileextra',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pathfinderprofileextra',
            name='gmail',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pathfinderprofileextra',
            name='languages',
            field=models.CharField(blank=True, help_text='English, French, Yoruba', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pathfinderprofileextra',
            name='title',
            field=models.CharField(blank=True, help_text='e.g. Software Engineer, Data Scientist', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pathfinderprofileextra',
            name='work_experience',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PathfinderCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pathfinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathfinder_certifications', to='profiles.pathfinderprofileextra')),
            ],
        ),
        migrations.CreateModel(
            name='PathfinderEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pathfinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathfinder_education', to='profiles.pathfinderprofileextra')),
            ],
        ),
        migrations.CreateModel(
            name='PathfinderSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pathfinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathfinder_skills', to='profiles.pathfinderprofileextra')),
            ],
        ),
    ]
