# Generated by Django 5.2.7 on 2026-02-28 23:33

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_city_enablerprofileextra_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='document',
            field=models.FileField(max_length=255, upload_to=profiles.models.credential_file_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=profiles.models.recipe_image_file_path),
        ),
    ]
