# Generated by Django 5.2.7 on 2026-03-12 11:40

import cloudinary_storage.storage
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_credential_document_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='document',
            field=models.FileField(max_length=255, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=profiles.models.credential_file_path),
        ),
    ]
