# Generated by Django 5.2.13 on 2026-04-20 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_address_alter_profile_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform_url',
            field=models.URLField(max_length=150, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
