# Generated by Django 5.2.17 on 2026-09-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_sociallink_platform_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform_url',
            field=models.URLField(max_length=150),
        ),
    ]
