# Generated by Django 5.2.7 on 2026-01-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_opportunity_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('voluteering', 'Volunteering'), ('internship', 'Internship'), ('scholarship', 'Scholarship'), ('job', 'Job'), ('grant', 'Grant')], default='voluteering', max_length=100),
        ),
    ]
