# Generated by Django 5.2.7 on 2026-02-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_opportunity'),
        ('bookmark', '0003_alter_opportunity_options_and_more'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity'),
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
    ]
