# Generated by Django 5.2.7 on 2026-04-03 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_alter_bookmark_opportunity_delete_opportunity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_pathfinders', to=settings.AUTH_USER_MODEL)),
                ('pathfinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('enabler', 'pathfinder')},
            },
        ),
    ]
