# Generated by Django 5.2.12 on 2026-04-03 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_alter_bookmark_opportunity_delete_opportunity'),
        ('profiles', '0006_alter_credential_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('pathfinder_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('enabler', 'pathfinder_profile')},
            },
        ),
    ]
