# Generated by Django 5.2.12 on 2026-04-04 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_profilebookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileBookmark',
        ),
    ]
