# Generated by Django 5.2.7 on 2026-04-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_bookmarkuser'),
        ('profiles', '0006_alter_credential_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkuser',
            name='pathfinder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='profiles.pathfinderprofileextra'),
        ),
    ]
