# Generated by Django 5.2.12 on 2026-04-17 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_alter_bookmarkuser_pathfinder'),
        ('profiles', '0008_alter_profile_address_alter_profile_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkEnabler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_pathfinders', to='profiles.enablerprofileextra')),
                ('pathfinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_enablers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pathfinder', 'enabler')},
            },
        ),
    ]
