# Generated by Django 5.2.7 on 2025-12-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_secret_key',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_otp_used',
            field=models.BooleanField(default=False),
        ),
    ]
