# Generated by Django 5.2.7 on 2025-12-25 04:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_database', '0005_alter_waitlistemail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reset_password_otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reset_password_otp_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reset_password_otp_used',
        ),
        migrations.AddField(
            model_name='waitlistemail',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('verification_type', models.CharField(choices=[('waitlist', 'Waitlist'), ('user_signup', 'User Signup'), ('password_reset', 'Password Reset')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification',
                'verbose_name_plural': 'Email Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='waitlistemail',
            name='verification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_email', to='user_database.emailverification'),
        ),
        migrations.DeleteModel(
            name='OtpToken',
        ),
    ]
