# Generated by Django 5.2.7 on 2026-01-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_database", "0006_remove_customuser_reset_password_otp_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="waitlistEmail",
        ),
    ]
