# Generated by Django 5.2.7 on 2026-01-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_database', '0007_delete_waitlistemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
