# Generated by Django 5.2.7 on 2026-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_database', '0008_remove_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('enabler', 'Enabler'), ('pathfinder', 'Pathfinder')], default='pathfinder', max_length=20),
        ),
    ]
