# Generated by Django 5.2.7 on 2026-04-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_database', '0010_customuser_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='last_resend_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('enabler', 'Enabler'), ('pathfinder', 'Pathfinder')], db_index=True, default='pathfinder', max_length=20),
        ),
    ]
