# Generated by Django 5.2.7 on 2025-10-28 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_customuser_bio_customuser_otp_secret_key_otptoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='otptoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
