# Generated by Django 5.2.7 on 2025-10-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_remove_otptoken_timestamp_otptoken_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptoken',
            name='code',
        ),
    ]
