# Generated by Django 5.2.12 on 2026-04-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_is_read_notification_read_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('server', 'Server'), ('personal', 'Personal')], default='system', max_length=10),
        ),
    ]
