# Generated by Django 5.2.13 on 2026-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_recipient_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
