"""
Django settings for Afrivate project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os 
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import  dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')


'''
Generate a new secret key for production and keep it secret.
from django.core.management.utils import get_random_secret_key
print(get_random_secret_key()) 
and set it as an environment variable.
'''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get("DEBUG","0"))) # set to 0 in production

if DEBUG:
    # Local deve
    SITE_DOMAIN = "http://127.0.0.1:8000"
    FRONTEND_URL = "http://localhost:3000"
else:
    # Production environment (Actual live URLs)
    SITE_DOMAIN = os.environ.get("SITE_DOMAIN",'https://afrivate-backend-production.up.railway.app')
    FRONTEND_URL = os.environ.get("FRONTEND_URL",'https://afrivate.org')

ALLOWED_HOSTS = []
ALLOWED_HOSTS.extend(
    filter(
        None,
        os.environ.get("ALLOWED_HOSTS", "").split(","),
    )
)


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    #dependencies
    'rest_framework', 
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    
    'drf_yasg',
    'sendgrid_backend',
    'django_filters',

    # for s3 strorage
    'storages',
    'cloudinary',

    # django apps
    'Authentication',
    'user_database',
    'profiles',
    'waitlist',
    'newsletter',
    "bookmark",
    'notifications',
    'applications',
    'opportunities',

    # signals
    # 'profiles.apps.ProfilesConfig'

    # allauth for social login
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # dj-rest-auth for rest endpoints for authentication, registration, password reset, etc.
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'rest_framework.authtoken',  # for token authentication, required by dj-rest-auth
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # for django allauth
]

ROOT_URLCONF = 'Afrivate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Afrivate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(
        os.environ.get("DB_URL"),
        conn_max_age=600,
        ssl_require= not True, # set back to true in production
    )
}

STORAGES = {
    "default": {
        # "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        "OPTIONS": {
            # Add any specific options here if needed
        },
    },
# This tells WhiteNoise to compress and cache your files (improves performance)
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MAX_PROFILE_PIC_MB = 5
PROFILE_PIC_ALLOWED_FORMATS = {"JPEG", "JPG", "PNG", "WEBP"}

# S3 endpoint
# AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
# AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
# AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
# AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL")   
# AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME")


# Optional, recommended
# AWS_S3_FILE_OVERWRITE = False
# AWS_DEFAULT_ACL = None


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# This is where collectstatic will put all files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Media files (for user uploads)
MEDIA_URL = '/media/'  # or any prefix you choose

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user_database.CustomUser'

AUTHENTICATION_BACKENDS = [
    'Authentication.backends.CustomAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend', # for django allauth
]

# Email configuration
# EMAIL_BACKEND = os.getenv("DJANGO_EMAIL_BACKEND") # For Production purposes
# SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
# DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# SENDGRID_SANDBOX_MODE_IN_DEBUG = False
# ACCOUNT_EMAIL_VERIFICATION = "mandatory"

EMAIL_BACKEND = os.getenv("DJANGO_EMAIL_BACKEND")
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'profiles.utils.custom_exception_handler',
}

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Authorization header using Bearer scheme. Example: Bearer <token>",
        }
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1), # to be changed to hours in production
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1), # to be changed to weeks in production
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': True,
    'TOKEN_OBTAIN_SERIALIZER': 'user_database.serializers.CustomTokenObtainPairSerializer',
}

# RAW_ORIGINS = os.environ.get("TRUSTED_ORIGINS", "http://localhost:3000").split(",")
# CORS_ALLOWED_ORIGINS = RAW_ORIGINS
# CSRF_TRUSTED_ORIGINS = RAW_ORIGINS
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # local frontend
    'https://afrivate-tech.github.io',
    'https://afrivate-backend-production.up.railway.app',
    'https://afrivate.org',
    'https://www.afrivate.org', 
    'https://afrivate-volunteer-module-frontend.vercel.app'
]

CSRF_TRUSTED_ORIGINS = [
        'https://afrivate-backend-production.up.railway.app',
        'https://afrivate.org', 'https://www.afrivate.org', 'https://afrivate-volunteer-module-frontend.vercel.app'
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours in seconds, COULD BE REDUCED FOR BETTER SECURITY


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO', # INFO, ERROR
            'propagate': False, # change to False to prevent duplicate logs if root logger is also logging
        },
        'waitlist': {  
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

BLACKLISTED_DOMAINS = {
    "mailinator.com",
    "tempmail.com",
    "10minutemail.com",
    "guerrillamail.com",
    "yopmail.com",
    "trashmail.com",
    "dispostable.com",
}

ALLOWED_DOMAINS = {
    "gmail.com",
    "yahoo.com",
    "outlook.com",
    "icloud.com",
}

BAD_PATTERNS = [
    r"^test\d*@",
    r"^admin@",
    r"^info@",
    r"^support@",
    r"^no[-_]?reply@",
    r"\d{6,}",          # long digit runs
    r"(spam|fake|junk)",
]


APPEND_SLASH = True

# django allauth settings for social login, currently only google but can be extended to others in the future
SITE_ID = 1 # required for django allauth
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_ADAPTER = 'Authentication.adapter.CustomSocialAccountAdapter'

ACCOUNT_LOGIN_METHODS = {'email'}  
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

CLOUDINARY_STORAGE = {
    "SECURE": True,
    "RESOURCE_TYPE": "auto",
    'CLOUD_NAME': os.getenv("CLOUDINARY_CLOUD_NAME"),
    'API_KEY': os.getenv("CLOUDINARY_API_KEY"),
    'API_SECRET': os.getenv("CLOUDINARY_API_SECRET")
}
