"""
Django settings for Afrivate project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os 
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import  dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')


'''
Generate a new secret key for production and keep it secret.
from django.core.management.utils import get_random_secret_key
print(get_random_secret_key()) 
and set it as an environment variable.
'''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get("DEBUG","0"))) # set to 0 in production

if DEBUG:
    SITE_DOMAIN = "http://127.0.0.1:8000"
    FRONTEND_URL = "http://localhost:3000"
else:
    # Fall back to the Railway/Vercel URLs if env vars are absent in production.
    SITE_DOMAIN = os.environ.get("SITE_DOMAIN",'https://afrivate-backend-production.up.railway.app')
    FRONTEND_URL = os.environ.get("FRONTEND_URL",'https://afrivate-volunteer-module-frontend.vercel.app')

ALLOWED_HOSTS = []
ALLOWED_HOSTS.extend(
    filter(
        None,
        [
            h.replace("https://", "").replace("http://", "").strip()
            for h in os.environ.get("ALLOWED_HOSTS", "").split(",")
        ],
    )
)


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    #dependencies
    'rest_framework', 
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    
    'drf_yasg',
    'sendgrid_backend',
    'django_filters',

    # for s3 strorage
    'storages',
    'cloudinary',

    # django apps
    'Authentication',
    'user_database',
    'profiles',
    'waitlist',
    "bookmark",
    'notifications',
    'applications',
    'opportunities',

    # allauth for social login
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # dj-rest-auth for rest endpoints for authentication, registration, password reset, etc.
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'rest_framework.authtoken',  # for token authentication, required by dj-rest-auth
    'django_celery_results',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # for django allauth
]

ROOT_URLCONF = 'Afrivate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Afrivate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ssl_require=not DEBUG encrypts DB connections in production (DEBUG=0) and disables
# SSL for local dev (DEBUG=1), where the local PostgreSQL instance typically has no cert.
# A previous version had ssl_require=not True (always False) — that was a security bug.
DATABASES = {
    "default": dj_database_url.parse(
        os.environ.get("DB_URL"),
        conn_max_age=600,
        ssl_require=not DEBUG,
    )
}

STORAGES = {
    "default": {
        # "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        "OPTIONS": {
            # Add any specific options here if needed
        },
    },
# This tells WhiteNoise to compress and cache your files (improves performance)
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MAX_PROFILE_PIC_MB = 5
PROFILE_PIC_ALLOWED_FORMATS = {"JPEG", "JPG", "PNG", "WEBP"}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# This is where collectstatic will put all files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Media files (for user uploads)
MEDIA_URL = '/media/'  # or any prefix you choose

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user_database.CustomUser'

AUTHENTICATION_BACKENDS = [
    'Authentication.backends.CustomAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend', # for django allauth
]

# Email configuration
# Django email framework — used wherever send_mail() / EmailMessage is called.
EMAIL_BACKEND = os.getenv("DJANGO_EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

RESEND_API_KEY = os.getenv("RESEND_API_KEY")

# ScopedRateThrottle is used project-wide. Each auth view sets throttle_scope to one
# of the keys below. The counts are stored in the Redis cache (CACHES["default"]).
# To add a new scope: add a key here AND set throttle_scope on the view class.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'profiles.utils.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth_register':        '5/hour',
        'auth_login':           '10/hour',
        'auth_otp_verify':      '10/hour',
        'auth_resend_otp':      '5/hour',
        'auth_forgot_password': '5/hour',
        'auth_password_reset':  '10/hour',
    },
}

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Authorization header using Bearer scheme. Example: Bearer <token>",
        }
    }
}

# ROTATE_REFRESH_TOKENS + BLACKLIST_AFTER_ROTATION: every token refresh issues a new
# refresh token and immediately invalidates the old one. This means a stolen refresh
# token can only be used once before it is blacklisted.
# CustomTokenObtainPairSerializer injects 'role' and 'email' into the JWT payload
# so the frontend can read them without a separate /me endpoint.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=6),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': True,
    'TOKEN_OBTAIN_SERIALIZER': 'user_database.serializers.CustomTokenObtainPairSerializer',
}

# CORS_ALLOWED_ORIGINS env var (comma-separated) is merged with the hardcoded defaults
# at startup, using a set to deduplicate. This lets new frontend origins (e.g. a staging
# deployment) be added via Railway env vars without touching code.
_CORS_ORIGINS_DEFAULT = [
    "http://localhost:3000",
    "https://afrivate-tech.github.io",
    "https://afrivate-backend-production.up.railway.app",
    "https://afrivate.org",
    "https://www.afrivate.org",
    "https://afrivate-volunteer-module-frontend.vercel.app",
]
CORS_ALLOWED_ORIGINS = list(
    {
        *_CORS_ORIGINS_DEFAULT,
        *[o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()],
    }
)

CSRF_TRUSTED_ORIGINS = [
        'https://afrivate-backend-production.up.railway.app',
        'https://afrivate.org', 'https://www.afrivate.org', 'https://afrivate-volunteer-module-frontend.vercel.app'
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour in seconds


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO', # INFO, ERROR
            'propagate': False, # change to False to prevent duplicate logs if root logger is also logging
        },
        'waitlist': {  
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

BLACKLISTED_DOMAINS = {
    "mailinator.com",
    "tempmail.com",
    "10minutemail.com",
    "guerrillamail.com",
    "yopmail.com",
    "trashmail.com",
    "dispostable.com",
}

ALLOWED_DOMAINS = {
    "gmail.com",
    "yahoo.com",
    "outlook.com",
    "icloud.com",
}

BAD_PATTERNS = [
    r"^test\d*@",
    r"^admin@",
    r"^info@",
    r"^support@",
    r"^no[-_]?reply@",
    r"\d{6,}",          # long digit runs
    r"(spam|fake|junk)",
]


APPEND_SLASH = True

# django allauth settings for social login, currently only google but can be extended to others in the future
SITE_ID = 1 # required for django allauth
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_ADAPTER = 'Authentication.adapter.CustomSocialAccountAdapter'

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv("GOOGLE_CLIENT_ID"),
            'secret': os.getenv("GOOGLE_CLIENT_SECRET"),
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

# Cloudinary is the default storage backend (STORAGES["default"]) for all media files:
# profile pictures (MediaCloudinaryStorage) and credentials/resumes (RawMediaCloudinaryStorage).
# RESOURCE_TYPE="auto" lets Cloudinary detect whether the upload is an image, video, or raw file.
CLOUDINARY_STORAGE = {
    "SECURE": True,
    "RESOURCE_TYPE": "auto",
    'CLOUD_NAME': os.getenv("CLOUDINARY_CLOUD_NAME"),
    'API_KEY': os.getenv("CLOUDINARY_API_KEY"),
    'API_SECRET': os.getenv("CLOUDINARY_API_SECRET")
}

# Redis is shared between three consumers: Django cache (used by ScopedRateThrottle),
# Celery broker, and Celery result backend. A single REDIS_URL feeds all three.
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# celery configuration for background tasks (like sending emails, processing notifications, etc.)

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Lagos'