# Generated by Django 5.2.7 on 2026-02-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='opportunities.opportunity'),
        ),
    ]
