# Generated by Django 5.2.7 on 2026-03-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_resume'),
        ('profiles', '0006_alter_credential_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='profile_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.credential'),
        ),
    ]
