# Generated by Django 5.2.7 on 2025-12-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_database', '0003_waitlistemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
