# Generated by Django 5.2.7 on 2025-12-16 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_database', '0004_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistemail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Waitlist Email', 'verbose_name_plural': 'Waitlist Emails'},
        ),
        migrations.AddField(
            model_name='waitlistemail',
            name='referral_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='waitlistemail',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterModelTable(
            name='waitlistemail',
            table='waitlist_emails',
        ),
    ]
