# Generated by Django 5.2.7 on 2026-02-19 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(choices=[('voluteering', 'Volunteering'), ('internship', 'Internship'), ('scholarship', 'Scholarship'), ('job', 'Job'), ('grant', 'Grant')], db_index=True, default='voluteering', max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
                'unique_together': {('title', 'link')},
            },
        ),
    ]
