# Generated by Django 5.2.7 on 2026-02-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('volunteering', 'Volunteering'), ('internship', 'Internship'), ('scholarship', 'Scholarship'), ('job', 'Job'), ('grant', 'Grant')], db_index=True, default='voluteering', max_length=100),
        ),
    ]
