# Generated by Django 5.2.7 on 2026-02-27 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_alter_opportunity_opportunity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, related_name='created_opportunities', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('volunteering', 'Volunteering'), ('internship', 'Internship'), ('scholarship', 'Scholarship'), ('job', 'Job'), ('grant', 'Grant')], db_index=True, default='volunteering', max_length=100),
        ),
    ]
