# Generated by Django 5.2.7 on 2026-06-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_alter_opportunity_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('volunteering', 'Volunteering'), ('internship', 'Internship'), ('scholarship', 'Scholarship'), ('mentorship', 'Mentorship'), ('fellowship', 'Fellowship'), ('contract', 'Contract'), ('full_time', 'Full-time'), ('part_time', 'Part-time')], db_index=True, default='volunteering', max_length=100),
        ),
    ]
