# Generated by Django 5.2.17 on 2026-09-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_opportunity_target_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='role_skill_tags',
            field=models.JSONField(blank=True, default=list, help_text='List of skills developed in this opportunity'),
        ),
    ]
