# Generated by Django 5.2.17 on 2026-09-01 11:00

import django.db.models.deletion
import organizations.models
import organizations.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('organization_type', models.CharField(choices=[('ngo', 'NGO'), ('company', 'Company'), ('school', 'School'), ('government', 'Government'), ('community_group', 'Community Group'), ('other', 'Other')], db_index=True, max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('registry_type', models.CharField(blank=True, choices=[('rc', 'RC — Private company limited by shares'), ('bn', 'BN — Registered business name'), ('it', 'IT — Incorporated Trustees'), ('other', 'Other (non-Nigerian equivalent)')], max_length=10, null=True)),
                ('registry_id', models.CharField(blank=True, max_length=100, null=True)),
                ('registry_verified_at', models.DateTimeField(blank=True, null=True)),
                ('scuml_id', models.CharField(blank=True, max_length=100, null=True)),
                ('scuml_verified_at', models.DateTimeField(blank=True, null=True)),
                ('tier', models.CharField(choices=[('tier_1', 'Tier 1 — Registered & Verified'), ('tier_2', 'Tier 2 — Community-Referenced'), ('tier_3', 'Tier 3 — Self-Declared / Pending')], db_index=True, default='tier_3', max_length=10)),
                ('tier_status', models.CharField(choices=[('pending_review', 'Pending Review'), ('active', 'Active'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations_created', to=settings.AUTH_USER_MODEL)),
                ('vouched_by_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouched_organizations', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('cac_certificate', 'CAC Certificate'), ('scuml_certificate', 'SCUML Certificate'), ('letterhead', 'Organizational Letterhead'), ('proof_of_work_photo', 'Proof of Work (Photo)'), ('proof_of_work_video', 'Proof of Work (Video)'), ('recognition_letter', 'Recognition Letter'), ('other', 'Other')], db_index=True, max_length=30)),
                ('file', models.FileField(max_length=255, storage=organizations.storage.PrivateRawMediaCloudinaryStorage(), upload_to=organizations.models.org_document_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
                ('reviewed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_org_documents', to='adminpanel.adminuser')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('x', 'X'), ('tiktok', 'TikTok'), ('other', 'Other')], max_length=15)),
                ('url', models.URLField(max_length=300)),
                ('activity_verified', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('organization', 'Organization'), ('representative', 'Representative')], db_index=True, max_length=20)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('tier_upgraded', 'Tier Upgraded'), ('tier_downgraded', 'Tier Downgraded'), ('suspended', 'Suspended'), ('reinstated', 'Reinstated')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_actions', to='adminpanel.adminuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRepresentative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('role_title', models.CharField(max_length=100)),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('appointment_letter', models.FileField(blank=True, max_length=255, null=True, storage=organizations.storage.PrivateRawMediaCloudinaryStorage(), upload_to=organizations.models.representative_letter_file_path)),
                ('phone_number', models.CharField(max_length=20)),
                ('social_media_url', models.URLField(max_length=300)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.JSONField(blank=True, default=list)),
                ('verification_call_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_representative_roles', to=settings.AUTH_USER_MODEL)),
                ('verified_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_representatives', to='adminpanel.adminuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
