# Generated by Django 5.2.17 on 2026-09-08 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tier_2_admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verificationauditlog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('tier_upgraded', 'Tier Upgraded'), ('tier_downgraded', 'Tier Downgraded'), ('suspended', 'Suspended'), ('reinstated', 'Reinstated'), ('info_requested', 'More Information Requested'), ('revoked', 'Revoked')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationVouch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vouch_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_vouches_submitted', to=settings.AUTH_USER_MODEL)),
                ('from_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouches_given', to='organizations.organization')),
                ('to_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouches_received', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('from_organization', 'to_organization')},
            },
        ),
    ]
