# Generated by Django 5.2.17 on 2026-09-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_tier_2_admin_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
